apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeds-api
  labels:
    app: feeds-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feeds-api
  template:
    metadata:
      labels:
        app: feeds-api
    spec:
      containers:
      - name: udagram-feeds-api
        image: gzamorasosa12/udagram-feeds-api
        ports:
        - containerPort: 8082
