apiVersion: v1
kind: Service
metadata:
  labels:
    app: feeds-api
  name: feeds-api-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/feeds-api-svc
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: feeds-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}